#!/usr/bin/env bash
{
  # shellcheck disable=SC2168
  local IMPLEMENT="Symfony"
  # shellcheck disable=SC2168
  local PATH_MENU="${IMPLEMENT,,}.tasks"

  _mod_TITLE="$IMPLEMENT https://symfony.com/ \nSelect an option:"

  _mod_MAIN=(
    "${IMPLEMENT,,}:project:config,      $PATH_MENU.menu.show_config_project,          Project config,       Settings established in the project"
    "${IMPLEMENT,,}:console,             $PATH_MENU.menu.console,                      Console,              $IMPLEMENT Console"
    "${IMPLEMENT,,}:docker,              docker.tasks.menu.main,                       Docker,               Dockerization management in the project"
    "${IMPLEMENT,,}:permissions:fix,     $PATH_MENU.menu.fix_permissions,              Fix permissions,      Apply permissions"
    "${IMPLEMENT,,}:database,            mysql.tasks.menu.main,                        Database,             Database Manager"
  )

  _mod_CREATE_ENVIRONMENT=(
    "${IMPLEMENT,,}:create,              $PATH_MENU.install.create_new_environment,   Create new app, "
    "${IMPLEMENT,,}:clone,               $PATH_MENU.install.clone_environment,        Clone existing app,   Clone from http://url.repository"
  )

  _mod_CREATE_ENVIRONMENT_VERSION=(
    "shortcut:off,    5,   Symfony 5.x,   This version works with PHP-7.x"
    "shortcut:off,    6,   Symfony 6.x,   This version works with PHP-8.x"
  )
}
