#!/usr/bin/env bash
set -euo pipefail

_mod_.run_command_app_cli(){
  # shellcheck disable=SC2145
  docker.tasks.main.dp_command_run "run --rm app_cli ${@}"
}

# ToDo: Review oficial documentation
_mod_.permissions_fix(){
  local PATH_APP="./app"
  ! common.tasks.directory.exists "$PATH_APP" && common.tasks.directory.create_recursive "$PATH_APP"
  common.tasks.command_line.run true false "sudo chown -R $USER:$USER $PATH_APP"
}

_mod_.symfony_console_run_command(){
  local COMMAND_RUN COMMAND_CUSTOM MSG VALUES SEARCH
  VALUES=""
  COMMAND_RUN="bin/console"

  MSG=$(common.tasks.message.msg_color warning 'Enter the command or press enter for more info:')
  COMMAND_CUSTOM=$(common.tasks.prompt.request_input "$MSG")

  if [[ -z "$COMMAND_CUSTOM" ]]; then
      while true; do
        MSG=$(common.tasks.message.msg_color warning 'Enter what you are looking for or press enter for the full list:')
        SEARCH=$(common.tasks.prompt.request_input "$MSG")
          if [[ -z "$SEARCH" ]]; then
              break
          else
              if [[ -n "$VALUES" ]]; then
                  VALUES="$VALUES|$SEARCH"
              else
                  VALUES="$SEARCH"
              fi
          fi
      done

      if [[ -n "$VALUES" ]]; then
          COMMAND_CUSTOM="list | egrep --color=always \"$VALUES\""
      else
          COMMAND_CUSTOM="list"
      fi
  fi

  _mod_.run_command_app_cli "$COMMAND_RUN $COMMAND_CUSTOM"
}
