#!/usr/bin/env bash
#declare -gA ALL_MENUS
#declare -a MENU=('tools,Tools, ' 'symfony,Install Symfony, ' 'magento,Coming soon - Install Magento | Wordpress | Prestashop | Drupal | React | Angular | Vue | Next, ')
#ALL_MENUS["MENU_INIT"]="${MENU[@]}"

_mod_INIT=(
  'tools,Tools, ESTE'
  'symfony,Install Symfony, '
  'magento,Coming soon Install Magento | Wordpress | Prestashop | Drupal | React | Angular | Vue | Next ')
#  'magento,Coming soon - Install Magento, '
#  'wordpress,Coming soon - Install Wordpress, '
#  'woocommerce,Coming soon - Install WooCommerce, '
#  'prestashop,Coming soon - Install Prestashop, '
#  'drupal,Coming soon - Install Drupal, '
#  'react,Coming soon - Install React, '
#  'angular,Coming soon - Install Angular, '
#  'vue,Coming soon - Install Vue, '
#  'next,Coming soon - Install Next, '
#)