#!/usr/bin/env bash
set -euo pipefail
{
  # shellcheck disable=SC2168
  local PATH_MENU="efde.tasks"

  _mod_TITLE="EFDE | Easy and Fast Developer Environment\nSelect an option:"

  _mod_MAIN=(
    "efde:info,             $PATH_MENU.menu.efde,                     Efde config,            Settings and configurations"
    "symfony:install,       symfony.tasks.menu.create_environment,    Symfony,                Install for Symfony (WebApp or Apis)"
    "wordpress:install,     wordpress.tasks.menu.create_environment,  Wordpress,              Install for Wordpress and Woocommerce"
    "                   ,   _______________________________________,  _____________________,  _____________________________________"
    "laravel:install,       $PATH_MENU.menu.coming_soon,              Install Laravel,        Coming Soon"
    "magento:install,       $PATH_MENU.menu.coming_soon,              Install Magento,        Coming Soon"
    "woocommerce:install,   $PATH_MENU.menu.coming_soon,              Install Woocomerce,     Coming Soon"
    "prestashop:install,    $PATH_MENU.menu.coming_soon,              Install Prestashop,     Coming Soon"
    "django:install,        $PATH_MENU.menu.coming_soon,              Install Django,         Coming Soon"
    "efde:tools,            $PATH_MENU.menu.coming_soon,              Tools for developers,   Coming Soon"
  )

  _mod_EFDE=(
    "efde:info:github,          $PATH_MENU.main.more_info,                More info,              Show project EFDE"
    "efde:config,               $PATH_MENU.menu.config,                   Global configs,         Efde Global Settings"
    "efde:shortcuts,            $PATH_MENU.menu.shortcuts,                Show shortcuts,         Show shortcuts"
    "efde:report,               $PATH_MENU.main.report_github,            Report on github ,      Report Bug | Improvements | New Features | others"
    "efde:update,               $PATH_MENU.main.efde_update,              Update,                 Check update and downloads"
    "efde:uninstall,            $PATH_MENU.main.efde_uninstall,           Uninstall,              Uninstall from computer"
  )

  # TOOLS
  _mod_TOOLS=(
    "tools:portainer,   portainerfunction,      Portainer.io,     https://portainer.io/,"
    "tools:domains,     tools.tasks.domains,    Local domains,    /etc/hosts,"
  )

  # CONFIGURATION
  _mod_CONFIG=(
    "efde:config:show,    $PATH_MENU.menu.config_show,    Show,   Show project EFDE"
    "efde:config:set,     $PATH_MENU.config.set_config,   Set,    Set config"
  )

  _mod_CONFIG_SET_LANGUAGE=(
    "shortcut:off,    es_ES,    es_ES,    Spanish"
    "shortcut:off,    en_US,    en_US,    English"
    "shortcut:off,    pt_PT,    pt_PT,    Portuguese"
  )
}