#!/usr/bin/env bash
set -euo pipefail
{
  # shellcheck disable=SC2168
  local PATH_MENU="efde.tasks"

  _mod_MAIN=(
    "$PATH_MENU.menu.main,Efde config , Settings and configurations"
    "symfony.tasks.menu.create_environment,Install Symfony, Dockerization for symfony (WebApp or Apis)"
    "$PATH_MENU.menu.tools,Tools,Tools for developers"
  )

  _mod_EFDE=(
    "$PATH_MENU.main.more_info,More info,Show project EFDE"
    "$PATH_MENU.menu.config,Global configs,Efde Global Settings"
    "$PATH_MENU.main.report_github,Report on github , Report Bug | Improvements | New Features | others"
    "$PATH_MENU.main.efde_update,Update, Check update and downloads"
    "$PATH_MENU.main.efde_uninstall,Uninstall, Uninstall from computer"
  )

  # TOOLS
  _mod_TOOLS=(
    "portainerfunction,Portainer.io, https://portainer.io/"
    "domains.function,Local domains, /etc/hosts,"
  )

  # CONFIGURATION
  _mod_CONFIG=(
    "$PATH_MENU.menu.config_show,Show,Show project EFDE"
    "$PATH_MENU.config.set_config,Set, Set config"
  )

  _mod_CONFIG_SET_LENGUAGE=(
    "es_ES,es_ES, Spanish"
    "en_US,en_US, English"
    "pt_PT,pt_PT, Portuguese"
  )
}