#!/usr/bin/env bash

_mod_MAIN=(
  'symfony.tasks.menu.show_config_efde,EFDE show config, '
  'console,Console, '
  'docker,Docker, '
)

_mod_CREATE_ENVIRONMENT=(
  'symfony.tasks.install.create_new_environment,Create new app, '
  'symfony.tasks.install.clone_environment,Clone existing app, '
)

_mod_CREATE_ENVIRONMENT_VERSION=(
  '5,Symfony 5.x,This version works with PHP-7.x'
  '6,Symfony 6.x,This version works with PHP-8.x'
)

