#!/usr/bin/env bash
{
  # shellcheck disable=SC2168
  local IMPLEMENT="Laravel"
  # shellcheck disable=SC2168
  local PATH_MENU="${IMPLEMENT,,}.tasks"

  _mod_TITLE="$IMPLEMENT https://laravel.com/ \nSelect an option:"

  _mod_MAIN=(
    "${IMPLEMENT,,}:project:config,      $PATH_MENU.menu.show_config_project,           Project config,                 Settings established in the project"
    "${IMPLEMENT,,}:console,             $PATH_MENU.menu.console,                       Artisan,                        $IMPLEMENT Console"
    "${IMPLEMENT,,}:docker,              docker.tasks.menu.main,                        Docker,                         Dockerization management in the project"
    "${IMPLEMENT,,}:permissions:fix,     $PATH_MENU.menu.fix_permissions,               Fix permissions,                Apply permissions"
    "${IMPLEMENT,,}:database,            mysql.tasks.menu.main,                         Database,                       Database Manager"
  )

  _mod_CREATE_ENVIRONMENT=(
    "${IMPLEMENT,,}:install:new,                 $PATH_MENU.install.new_environment,            Create new project,             Use latest version available"
    "${IMPLEMENT,,}:install:clone,               $PATH_MENU.install.clone_environment,          Clone existing project,         Clone from http://url.repository"
  )

  _mod_CREATE_ENVIRONMENT_VERSION=(
    "${IMPLEMENT,,}:doc:compatibility,    $PATH_MENU.main.see_compatibility_versions,   See versions compatibility,"
    "shortcut:off,                        9,                                            Laravel 9.x,                    This version works from PHP 8.0"
    "shortcut:off,                        10,                                           Laravel 10.x,                   This version works from PHP 8.1"
    "shortcut:off,                        11,                                           Laravel 11.x,                   This version works with PHP 8.2"
    "shortcut:off,                        12,                                           Laravel 12.x,                   This version works with PHP 8.2"
  )
}
