#!/usr/bin/env bash
{
  # shellcheck disable=SC2168
  local IMPLEMENT="Laravel"
  # shellcheck disable=SC2168
  local PREFIX_TASKS="${IMPLEMENT,,}.tasks"

  _mod_TITLE="$IMPLEMENT https://laravel.com/ \nSelect an option:"

  _mod_MAIN=(
    "$PREFIX_TASKS.menu.config_show,                    Project config,                 Settings established in the project"
    "$PREFIX_TASKS.menu.console,                        Artisan,                        $IMPLEMENT Console"
    "docker.tasks.menu.main,                            Docker,                         Dockerization management in the project"
    "$PREFIX_TASKS.menu.fix_permissions,                Fix permissions,                Apply permissions"
    "mysql.tasks.menu.main,                             Database,                       Database Manager"
  )

  _mod_CREATE_ENVIRONMENT=(
    "$PREFIX_TASKS.install.new_environment,             Create new project,             Use latest version available"
    "$PREFIX_TASKS.install.clone_environment,           Clone existing project,         Clone from http://url.repository"
  )

  _mod_CREATE_ENVIRONMENT_VERSION=(
    "$PREFIX_TASKS.main.see_compatibility_versions,    See versions compatibility,"
    "9,                                                Laravel 9.x,                    This version works from PHP 8.0"
    "10,                                               Laravel 10.x,                   This version works from PHP 8.1"
    "11,                                               Laravel 11.x,                   This version works with PHP 8.2"
    "12,                                               Laravel 12.x,                   This version works with PHP 8.2"
  )
}
