#!/usr/bin/env bash
{
  # shellcheck disable=SC2168
  local IMPLEMENT="Wordpress"
  # shellcheck disable=SC2168
  local PATH_MENU="${IMPLEMENT,,}.tasks"

  _mod_TITLE="$IMPLEMENT https://wordpress.org/ \nSelect an option:"

  _mod_MAIN=(
    "${IMPLEMENT,,}:project:config,      $PATH_MENU.menu.show_config_project,          Project config,       Settings established in the project"
    "${IMPLEMENT,,}:cli,                 $PATH_MENU.menu.cli,                          WP-CLI,               $IMPLEMENT command line"
    "${IMPLEMENT,,}:docker,              docker.tasks.menu.main,                       Docker,               Dockerization management in the project"
    "${IMPLEMENT,,}:permissions:fix,     $PATH_MENU.menu.fix_permissions,              Fix permissions,      Apply permissions"
    "${IMPLEMENT,,}:database,            mysql.tasks.menu.main,                        Database,             Database Manager"
  )

  _mod_CREATE_ENVIRONMENT=(
    "${IMPLEMENT,,}:install:new,                 $PATH_MENU.install.new_environment,          Create new project,        Use latest version available"
    "${IMPLEMENT,,}:install:clone,               $PATH_MENU.install.clone_environment,        Clone existing project,    Choose PHP version and clone your git repository"
  )

  _mod_CREATE_ENVIRONMENT_VERSION=(
    "${IMPLEMENT,,}:doc:compatibility,  $PATH_MENU.main.see_compatibility_versions,   See versions compatibility,"
    "shortcut:off,                      5.6,                                          PHP 5.6,"
    "shortcut:off,                      7.1,                                          PHP 7.1,"
    "shortcut:off,                      7.2,                                          PHP 7.2,"
    "shortcut:off,                      7.3,                                          PHP 7.3,"
    "shortcut:off,                      7.4,                                          PHP 7.4,"
    "shortcut:off,                      8.0,                                          PHP 8.0,"
    "shortcut:off,                      8.1,                                          PHP 8.1,"
    "shortcut:off,                      8.2,                                          PHP 8.2,"
    "shortcut:off,                      8.3,                                          PHP 8.3,"
    "shortcut:off,                      8.4,                                          PHP 8.4, Coming Soon"
    "shortcut:off,                      8.x,                                          PHP 8.x, Coming Soon"
  )
}
