#!/usr/bin/env bash
{
  # shellcheck disable=SC2168
  local IMPLEMENT="Wordpress"
  # shellcheck disable=SC2168
  local PREFIX_TASKS="${IMPLEMENT,,}.tasks"

  _mod_TITLE="$IMPLEMENT https://wordpress.org/ \nSelect an option:"

  _mod_MAIN=(
    "$PREFIX_TASKS.menu.config_show,               Project config,       Settings established in the project"
    "$PREFIX_TASKS.menu.cli,                       WP-CLI,               $IMPLEMENT command line"
    "docker.tasks.menu.main,                       Docker,               Dockerization management in the project"
    "$PREFIX_TASKS.menu.permissions_fix,           Fix permissions,      Apply permissions"
    "mysql.tasks.menu.main,                        Database,             Database Manager"
  )

  _mod_CREATE_ENVIRONMENT=(
    "$PREFIX_TASKS.install.new_environment,        Create new project,        Use latest version available"
    "$PREFIX_TASKS.install.clone_environment,      Clone existing project,    Choose PHP version and clone your git repository"
  )

  _mod_CREATE_ENVIRONMENT_VERSION=(
    "$PREFIX_TASKS.main.see_compatibility_versions,    See versions compatibility,"
    "5.6,                                              PHP 5.6,"
    "7.1,                                              PHP 7.1,"
    "7.2,                                              PHP 7.2,"
    "7.3,                                              PHP 7.3,"
    "7.4,                                              PHP 7.4,"
    "8.0,                                              PHP 8.0,"
    "8.1,                                              PHP 8.1,"
    "8.2,                                              PHP 8.2,"
    "8.3,                                              PHP 8.3,"
    "8.4,                                              PHP 8.4, Coming Soon"
    "8.x,                                              PHP 8.x, Coming Soon"
  )
}
