#!/usr/bin/env bash
{
  # shellcheck disable=SC2168
  local IMPLEMENT="Docker"
  # shellcheck disable=SC2168
  local PREFIX_MENU="${IMPLEMENT,,}.tasks.menu"

  _mod_TITLE="$IMPLEMENT https://www.docker.com/ \nSelect an option:"

  _mod_MAIN=(
    "$PREFIX_MENU.build,         Build,        Build or Re-Build the project containers"
    "$PREFIX_MENU.show,          Show,         Show Process Status containers"
    "$PREFIX_MENU.start,         Start,        Start containers of project"
    "$PREFIX_MENU.restart,       Restart,      Restart containers of project"
    "$PREFIX_MENU.stop,          Stop,         Stop containers of project"
    "$PREFIX_MENU.logs,          Logs,         Inspect environment logs"
    "$PREFIX_MENU.entry,         Entry,        Enter the indicated container"
    "$PREFIX_MENU.command,       Run command,  Run command in container. Example: bash, cp, rm"
    "$PREFIX_MENU.stop_all,      All Stop,     Stops all containers running on the computer"
    "$PREFIX_MENU.apache_stop,   Apache Stop,  Apache2 stop service"
    "$PREFIX_MENU.down,          Down,         Destroy all project containers and networks"
    "$PREFIX_MENU.recipe_see,    See recipe,   See recipe docker-compose.yml"
  )
}
