#!/usr/bin/env bash
set -euo pipefail
{
  _mod_.main(){
    common.tasks.menu.show "$symfony_props_menu_TITLE" "${symfony_props_menu_MAIN[@]}"
  }

  _mod_.create_environment(){
    common.tasks.menu.show "$symfony_props_menu_TITLE" "${symfony_props_menu_CREATE_ENVIRONMENT[@]}"
  }

  _mod_.create_environment_version(){
    common.tasks.menu.show "$symfony_props_menu_TITLE" "${symfony_props_menu_CREATE_ENVIRONMENT_VERSION[@]}"
  }

  _mod_.show_config_project(){
    efde.tasks.project.config_show
    if common.tasks.prompt.confirm_default_yes $(common.tasks.message.msg_color warning "Back to menu?"); then
      common.tasks.os.console_clear
      _mod_.main
    else
      exit
    fi
  }

  _mod_.permissions_fix(){
    symfony.tasks.main.permissions_fix
    _mod_.main
  }

  _mod_.console(){
    symfony.tasks.main.console_run_command
    _mod_.main
  }
}