#!/usr/bin/env bash
set -euo pipefail

CONFIG_FILE="config.env"
CONFIG_PATH="$EFDE_PATH_INSTALL/bin"
CONFIG_PATH_FILE="$CONFIG_PATH/$CONFIG_FILE"

_mod_.check_config() {
  if ! common.tasks.file.exists "$CONFIG_PATH_FILE"; then
    _mod_.create_config
  fi
  _mod_.load_config
}

_mod_.create_config() {
  common.tasks.message.warning "Crearemos tu configuracion"
  _mod_.set_config
}

_mod_.set_config(){
  #autoupdate #days
  #lenguaje #es_ES en_US pt_PT
  #my_options=("es_ES" "en_US" "pt_PT")
  #common.tasks.menu.show_menu --question="¿Que lenguaje?" --options="es_ES,en_US,pt_PT"
  result=$(common.tasks.menu.show_menu --question="¿Que lenguaje?" --options="es_ES,en_US,pt_PT")
  echo $result
  exit
  # Definir el array asociativo con los pares "key=value"
  declare -A env_vars=(
    [VERSION]=$(_mod_.set_config_version)
    [SO]=$(common.tasks.os.get_operating_system)
    [LAST_UPDATE]=$(common.tasks.datetime.get_formatted_datetime "%Y-%m-%d")
  )

  echo -e "$(_mod_.prepare_string_to_env env_vars)" > $CONFIG_PATH_FILE
}

_mod_.set_config_version() {
  echo $(efde.tasks.git.get_current_tag)
}

_mod_.load_config() {
  echo "load config"
}

_mod_.show_config() {
 echo "t"
}

# USAGED
# Call:
#   SETUP_ENVIRONMENT=(
#     [NAME]="MyName"
#     [CREATE_AT]="2000-01-01"
#     [IMPLEMENTION]="efde"
#   )
#   _mod_.prepare_string_to_env SETUP_ENVIRONMENT
#
# Response:
#   'NAME="MyName"\nCREATE_AT="2000-01-01"\nIMPLEMENTION="efde"'
_mod_.prepare_string_to_env(){
  local -n env_array=$1
  local env_str=""

  for key in "${!env_array[@]}"; do
    value="${env_array[$key]}"
    env_str+="\n$key=\"$value\""
  done

  env_str="${env_str:2}" # Remove firts \n

  echo "$env_str"
}

