#!/usr/bin/env bash
set -euo pipefail
{
  _mod_.run_global_efde(){
    ${GLOBAL_RUN_EFDE}
  }

  _mod_.coming_soon(){
    common.tasks.message.warning "We are excited about the upcoming release!"
    common.tasks.message.warning "Our team is hard at work to bring you the latest features and improvements."
    common.tasks.message.warning "Stay tuned for updates and follow the projects progress on ${EFDE_CORE_CONFIG['REPOSITORY']}."
    common.tasks.message.warning "Thank you for your patience, and remember to check back for the latest developments."
  }

  _mod_.more_info(){
    url="${EFDE_CORE_CONFIG['REPOSITORY']}?tab=readme-ov-file#easy-and-fast-development-environment-efde-"
    common.tasks.command_line.run false false "xdg-open $url"
    _mod_.run_global_efde
  }

  _mod_.report_github(){
    url="${EFDE_CORE_CONFIG['REPOSITORY']}/issues/new/choose"
    common.tasks.command_line.run false false "xdg-open $url"
    _mod_.run_global_efde
  }
}