#!/usr/bin/env bash
set -euo pipefail
{
  _mod_.main(){
    common.tasks.os.console_clear
    common.tasks.menu.show \
      --title "$efde_props_menu_TITLE" \
      --data "${efde_props_menu_MAIN[@]}"
  }

  _mod_.efde(){
    common.tasks.menu.show \
      --title "$efde_props_menu_TITLE" \
      --data "${efde_props_menu_EFDE[@]}"
  }

  _mod_.config(){
    common.tasks.menu.show \
      --title "$efde_props_menu_TITLE" \
      --data "${common_props_config_CONFIG[@]}"
  }

  _mod_.config_show(){
    common.tasks.config.show_config
    _mod_.config
  }

  _mod_.tools(){
    common.tasks.menu.show \
      --title "$efde_props_menu_TITLE" \
      --data "${efde_props_menu_TOOLS[@]}"
  }

  _mod_.coming_soon(){
    efde.tasks.main.coming_soon
    _mod_.main
  }

  _mod_.shortcuts_show(){
    common.tasks.shortcuts.show
  }
}
