version: '3'

services:
    nginx:
        build:
            context: .
            dockerfile: ./.docker/nginx/Dockerfile
        restart: always
        volumes:
            - ./app/:/var/www/html/
        ports:
            - 80:80
        networks:
            - symfony
        depends_on:
            - app
    app:
        build:
            context: .
            dockerfile: ./.docker/php/Dockerfile
        restart: always
        expose:
            - 9000
        volumes:
            - ./app/:/var/www/html/
        networks:
            - symfony
        depends_on:
            - db
    db:
        image: 'mariadb:10.4'
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        volumes:
            - ./.docker/db/db_data:/var/lib/mysql
        env_file: ./.docker/db/env
        ports:
            - 3306:3306
        networks:
            - symfony

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        restart: always
        env_file: ./.docker/phpmyadmin/env
        links:
            - db
        ports:
            - 8080:80
        networks:
            - symfony
        depends_on:
            - db
    #mailhog:
    #    image: mailhog/mailhog
    #    ports:
    #       - 1025:1025 # smtp server
    #       - 8025:8025 # web ui
    #    links:
    #       - app
    #    tty: true

networks:
    symfony:
volumes:
    db_data:
    symfony:
