#!/usr/bin/env bash
{
  # shellcheck disable=SC2168
  local IMPLEMENT="mysql"
    # shellcheck disable=SC2168
  local PREFIX_MENU="${IMPLEMENT,,}.tasks.menu"

  _mod_TITLE="MySQL\nSelect an option:"

  _mod_MAIN=(
    "$PREFIX_MENU.env_show,            Show variables,               Show values in ./.env file"
    "$PREFIX_MENU.query_run,           Run custom query,             Run custom query on your database"
    "$PREFIX_MENU.database_export,     Export database,              Export Database in ./dumps"
    "$PREFIX_MENU.database_import,     Import database,              Import Database from ./dumps"
    "$PREFIX_MENU.permissions,         Apply privileges,             Apply DATABASE:USER privileges"
    "$PREFIX_MENU.container_entry,     Entry container,"
    "docker.tasks.menu.command,        Run command line,             Run command in database container"
  )
}
