#!/usr/bin/env bash
{
  # shellcheck disable=SC2168
  PATH_MENU="mysql.tasks.menu"

  _mod_TITLE="Mysql\nSelect an option:"

  _mod_MAIN=(
    "mysql:env,               $PATH_MENU.env_show,            Show variables,               Show values in ./.env file"
    "mysql:db:query,          $PATH_MENU.query_run,           Run custom query,             Run custom query on your database"
    "mysql:db:export,         $PATH_MENU.database_export,     Export database,              Export Database in ./dumps"
    "mysql:db:import,         $PATH_MENU.database_import,     Import database,              Import Database from ./dumps"
    "mysql:db:permissions,    $PATH_MENU.permissions,         Apply privileges,             Apply DATABASE:USER privileges"
    "mysql:container,         $PATH_MENU.container_entry,     Entry container,"
    "mysql:run:script,        docker.tasks.menu.command,      Run command line,             Run command in 'database' container"
  )
}
