#!/usr/bin/env bash
set -euo pipefail

_mod_.run() {
  if [ "$#" -lt 3 ]; then
    local HELPER=""
    HELPER+="Error: At least three parameters are required:\n"
    HELPER+=" - FORCE_SHOW_CLI FORCE_SHOW_OUTPUT COMMAND_LINE\n"
    HELPER+="\n parameters:\n ${@}\n"
    HELPER+="\n Example:\n"
    HELPER+=" - $FUNCNAME FORCE_SHOW_CLI=true FORCE_SHOW_OUTPUT=true COMMAND_LINE\n"
    HELPER+=" - $FUNCNAME 1 0 'cd folder'"
    common.tasks.message.danger "$HELPER"
    return 1
  fi

  local FORCE_SHOW_CLI=$1
  local FORCE_SHOW_OUTPUT=$2
  shift 2
  local COMMAND_LINE="$@"

  if [[ "${EFDE_CONFIG_HOST['HOST_CLI_MODE']:-}" != "default" ]]; then
    FORCE_SHOW_CLI=$(_mod_.show_cli)
    FORCE_SHOW_OUTPUT=$(_mod_.show_output)
  fi

  if [ "${FORCE_SHOW_CLI}" = "true" ]; then
    common.tasks.message.info "# RUN CLI > ${COMMAND_LINE}"
  fi

  if [ "${FORCE_SHOW_OUTPUT}" = "true" ]; then
    eval "${COMMAND_LINE}"
  else
    eval "${COMMAND_LINE}" > /dev/null 2>&1
  fi
}

_mod_.show_cli() {
  case "${EFDE_CONFIG_HOST['HOST_CLI_MODE']:-}" in
    silent)                 echo "false"    ;;
    training | auditor)     echo "true"     ;;
    *)                      echo "false"    ;;
  esac
}

_mod_.show_output() {
  case "${EFDE_CONFIG_HOST['HOST_CLI_MODE']:-}" in
    silent | training)      echo "false"    ;;
    auditor)                echo "true"     ;;
    *)                      echo "false"    ;;
  esac
}