#!/usr/bin/env bash
set -euo pipefail

_mod_.check() {
  echo "Load " $(basename "${BASH_SOURCE[0]}")
}

_mod_.exists_function(){
  local FUNCTION_NAME=$1
  if [ "$(type -t "$FUNCTION_NAME")" = "function" ]; then
    return 0
  else
    common.tasks.message.danger "Error: Function '$FUNCTION_NAME' does not exist."
    return 1
  fi
}

# MMTodo: Prepare for debug
# Debug Call Stack
_mod_.debug_function_moment(){
    local func_last func_penultimate
    func_last=$(caller 0)
    func_penultimate=$(caller 1)
    common.tasks.message.warning "$(echo "$func_last" | awk '{print $3}')"
    echo -e "\n"
    #echo $func_penultimate
    #echo $(echo "$caller_info" | awk '{print $3}')
}