#!/usr/bin/env bash
set -euo pipefail

_mod_.debug(){
    local level="${2:-0}"
    local end="${3:-0}"
    local prefix=""

    if [ "$level" -eq 1 ]; then
      prefix+="├──"
    fi
    if [ "$level" -gt 1 ]; then
      for ((i=1; i<level; i++)); do
        prefix+="│   "
      done
      if [ "$end" -eq 0 ]; then
        prefix+="├──"
      else
        prefix+="└──"
      fi
    fi

    _mod_.print "$prefix $1" "debug"
}

_mod_.print(){
    local color_start=""
    local color_end=""
    if [ "$2" == "debug" ]; then
        local color_start="\033[1;35m"
        local color_end="\033[0m"
    fi

    if [ "$EFDE_MOD_DEBUG" = "true" ] ; then
      command printf "${color_start}$1${color_end}\n" 2>/dev/null
    fi
}

_mod_.danger(){
    local level="${2:-0}"
    if [ "$EFDE_MOD_DEBUG" = "true" ] ; then
      _mod_.debug "\033[1;31m$1\033[0m" $level
    else
      command printf "\033[1;31m$1\033[0m\n" 2>/dev/null
    fi
}