#!/usr/bin/env bash
set -euo pipefail

_mod_.get_operating_system() {
  local os=""
  case "$OSTYPE" in
    linux-gnu)   os="Linux"       ;;
    darwin*)     os="macOS"       ;;
    cygwin|msys) os="Windows"     ;;
    *)           os="Undefined" ;;
  esac
  echo "$os"
}

_mod_.has() {
  type "$1" >/dev/null 2>&1
}

_mod_.console_clear() {
  if [ -z "${GLOBAL_EFDE_CONFIG:-}" ] || [ -z "${GLOBAL_EFDE_CONFIG['HOST_SO']:-}" ]; then
    GLOBAL_EFDE_CONFIG['HOST_SO']="$(_mod_.get_operating_system)"
  fi

  case "${GLOBAL_EFDE_CONFIG['HOST_SO']}" in
    Linux) clear ;;
    *) common.tasks.message.danger "Operating system not configured" ;;
  esac
}