#!/usr/bin/env bash
set -euo pipefail

_mod_.get_operating_system() {
  local os=""
  case "$OSTYPE" in
    linux-gnu)   os="Linux"       ;;
    darwin*)     os="macOS"       ;;
    cygwin|msys) os="Windows"     ;;
    *)           os="Undefined" ;;
  esac
  echo "$os"
}

_mod_.has() {
  type "$1" >/dev/null 2>&1
}

_mod_.console_clear() {
  local COMMAND
  if [ -z "${EFDE_CONFIG_HOST:-}" ] || [ -z "${EFDE_CONFIG_HOST['HOST_SO']:-}" ]; then
    EFDE_CONFIG_HOST['HOST_SO']="$(_mod_.get_operating_system)"
  fi

  case "${EFDE_CONFIG_HOST['HOST_SO']}" in
    Linux) COMMAND="clear" ;;
    *)
      common.tasks.message.danger "Operating system not configured"
      return 1
      ;;
  esac

  # MMTodo: DANGER
  # if compact brings error when setting debug and running efde
  # ! common.tasks.config.get_efde_mode_debug && ${COMMAND}
  if ! common.tasks.config.get_efde_mode_debug; then
    ${COMMAND}
  fi
}