#!/usr/bin/env bash
set -euo pipefail

# Read a single char from /dev/tty, prompting with "$*"
# Note: pressing enter will return a null string. Perhaps a version terminated with X and then remove it in caller?
# See https://unix.stackexchange.com/a/367880/143394 for dealing with multi-byte, etc.
_mod_.get_keypress() {
  local REPLY IFS=
  printf >/dev/tty '%s' "$*"
  #[[ $ZSH_VERSION ]] && read -rk1 # Use -u0 to read from STDIN
  # See https://unix.stackexchange.com/q/383197/143394 regarding '\n' -> ''
  [[ $BASH_VERSION ]] && read </dev/tty -rn1
  printf '%s' "$REPLY"
}

# Get a y/n from the user, return yes=0, no=1 enter=$2
# Prompt using $1.
# If set, return $2 on pressing enter, useful for cancel or defualting
_mod_.get_yes_keypress() {
  local prompt="${1:-Are you sure [y/n]? }"
  local enter_return=$2
  local REPLY
  # [[ ! $prompt ]] && prompt="[y/n]? "
  while REPLY=$(_mod_.get_keypress "$prompt"); do
    [[ $REPLY ]] && printf '\n' # $REPLY blank if user presses enter
    case "$REPLY" in
    Y | y) return 0 ;;
    N | n) return 1 ;;
    '') [[ $enter_return ]] && return "$enter_return" ;;
    esac
  done
}

# Credit: http://unix.stackexchange.com/a/14444/143394
# Prompt to confirm, defaulting to NO on <enter>
# Usage: _mod_.confirm_default_no "Dangerous. Are you sure?" && action_function
_mod_.confirm_default_no() {
  local prompt="${*:-Are you sure} [y/N]? "
  _mod_.get_yes_keypress "$prompt" 1
}

# Prompt to confirm, defaulting to YES on <enter>
# Usage:
# _mod_.confirm_default_yes "question?" && action_function
_mod_.confirm_default_yes() {
  local prompt="${*:-Are you sure} [Y/n]? "
  _mod_.get_yes_keypress "$prompt" 0
}

_mod_.request_input() {
  read -r -p "$@" value
  echo $value
}
