#!/usr/bin/env bash
############################################################
# DANGER WARNING
# In this file YOU SHOULD NOT USE module calls
#   efde.tasks.*
#   common.tasks.*
#   common.tasks.message.info
############################################################
set -euo pipefail

DIRECTORY_TMP="${EFDE_CORE_PATH['TMP']}"

declare -gA EFDE_INIT=(
  [DEBUG]="${GLOBAL_EFDE_CONFIG['EFDE_MODE_DEBUG']}"
  [TMP]="${EFDE_CORE_PATH['TMP']}"
  [CONSOLE]="${EFDE_CORE_PATH['CONSOLE']}"
  #[INIT_MODULE]="common"
  #[INIT_PROPS]="config colours"
  #[TASKS]="config message menu os datetime git prompt file env_variable"
)

init.check_construct(){
  local MODULE_NAME="common"
  local IMPORT_FILE="core"
  local PATH_SOURCE="${EFDE_INIT['CONSOLE']}/$MODULE_NAME/$IMPORT_FILE"
  local PATH_TARGET="${EFDE_INIT['TMP']}/$MODULE_NAME.$IMPORT_FILE"

  [[ "${EFDE_INIT['DEBUG']}" == "true" ]] && rm -rf "$DIRECTORY_TMP"

  [ ! -d "${EFDE_INIT['TMP']}" ] && mkdir -p "${EFDE_INIT['TMP']}"; chmod +x "${EFDE_INIT['TMP']}"

  if [[ ! -f "$PATH_TARGET" ]]; then
      sed "/sed/! s/_mod_/$MODULE_NAME.$IMPORT_FILE/g" "$PATH_SOURCE" > "$PATH_TARGET"
  fi


  init.load_scripts "$PATH_TARGET"
  init.load_scripts "${EFDE_INIT['CONSOLE']}/$MODULE_NAME"
}

init.load_modules(){
  local PATH_TO_INSPECT="$@"
  local DIRECTORIES=$(find "$PATH_TO_INSPECT" -maxdepth 1 -type d ! -path "$PATH_TO_INSPECT" ! -name "$(basename "$PATH_TO_INSPECT")" -printf "%f\n")
  for DIRECTORY in $DIRECTORIES; do
    [ "$DIRECTORY" = "common" ] && continue

    PATH_TARGET="$PATH_TO_INSPECT/$DIRECTORY"
    local PATH_TASKS_EXISTS="$PATH_TARGET/tasks"
    if [ -d "$PATH_TASKS_EXISTS" ]; then
      init.load_scripts "$PATH_TARGET"
    else
      init.load_modules "$PATH_TARGET"
    fi
  done
}

init.load_scripts(){
  local FUNCTION_LOAD="common.core.load_module"
  if [ "$(type -t "$FUNCTION_LOAD")" = "function" ] ; then
    ${FUNCTION_LOAD} "$@"
  else
    source "$@"
  fi
}

init.main() {
  init.check_construct
  init.load_modules "${EFDE_INIT['CONSOLE']}"
  common.core.generate_extra_elements
}

init.main






