#!/usr/bin/env bash
set -euo pipefail

_mod_.main(){
  common.tasks.menu.show "$mysql_props_menu_TITLE" "${mysql_props_menu_MAIN[@]}"
}

_mod_.env_show(){
  cat "$(efde.tasks.implemention.get_current_path_env_file)" | grep -E "MYSQL|PMA"
  if common.tasks.prompt.confirm_default_yes $(common.tasks.message.msg_color warning "Back to menu?"); then
    common.tasks.os.console_clear
    _mod_.main
  else
    exit
  fi
}

_mod_.query_run(){
  mysql.tasks.main.run_custom_query
  _mod_.main
}

_mod_.container_entry(){
  mysql.tasks.main.container_entry
  _mod_.main
}

_mod_.database_export(){
  mysql.tasks.main.database_export
  _mod_.main
}

_mod_.database_import(){
  mysql.tasks.main.database_import
  _mod_.main
}

_mod_.permissions(){
  mysql.tasks.main.permissions
  _mod_.main
}

