#!/usr/bin/env bash
set -euo pipefail
{
  _mod_.main(){
    common.tasks.menu.show \
      --title "$laravel_props_menu_TITLE" \
      --data "${laravel_props_menu_MAIN[@]}"
  }

  _mod_.create_environment(){
    common.tasks.menu.show \
      --title "$laravel_props_menu_TITLE" \
      --data "${laravel_props_menu_CREATE_ENVIRONMENT[@]}"
  }

  _mod_.create_environment_version(){
    common.tasks.menu.show \
      --title "$laravel_props_menu_TITLE" \
      --data "${laravel_props_menu_CREATE_ENVIRONMENT_VERSION[@]}"
  }

  _mod_.config_show(){
    efde.tasks.project.config_show
    if common.tasks.prompt.confirm_default_yes $(common.tasks.message.msg_color warning "Back to menu?"); then
      common.tasks.os.console_clear
      _mod_.main
    else
      exit
    fi
  }

  _mod_.fix_permissions(){
    laravel.tasks.main.permissions_fix
    _mod_.main
  }

  _mod_.console(){
    laravel.tasks.main.console_run_command
    _mod_.main
  }
}