version: '3'

services:
    nginx:
        build:
            context: ./.docker/nginx
        image: efde/nginx
        #restart: unless-stopped
        depends_on:
            - app_fpm
        ports:
            - 80:80
        volumes:
            - ./app/:/app
        networks:
            - symfony
    app_fpm:
        build:
            context: ./.docker/php/${PHP_VERSION}/fpm
        image: efde/php-${PHP_VERSION}-fpm
        #restart: unless-stopped
        depends_on:
            - db
        expose:
            - 9000
        volumes:
            - ./app/:/app
        networks:
            - symfony
    app_cli:
        build:
            context: ./.docker/php/${PHP_VERSION}/cli
        image: efde/php-${PHP_VERSION}-cli
        #restart: unless-stopped
        depends_on:
            - db
        ports:
            - 35729:35729
        volumes:
            - ./app/:/app
        networks:
            - symfony
    db:
        image: 'mariadb:10.4'
        command: --default-authentication-plugin=mysql_native_password
        #restart: unless-stopped
        env_file: .env
        ports:
            - 3306:3306
        networks:
            - symfony

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        #restart: unless-stopped
        env_file: .env
        links:
            - db
        ports:
            - 8080:80
        networks:
            - symfony
        depends_on:
            - db
    #mailhog:
    #    image: mailhog/mailhog
    #    ports:
    #       - 1025:1025 # smtp server
    #       - 8025:8025 # web ui
    #    links:
    #       - app
    #    tty: true

networks:
    symfony:
volumes:
    symfony:
